apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
  labels:
    app: nginx-secret
spec:
  containers:
    - name: nginx-secret
      image: nginx
      ports:
        - containerPort: 8080
      volumeMounts:
      - name: secret
        mountPath: "/etc/secret"
        readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: secret-example
