apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: nginx
            args:
            - /bin/sh
            - -c
            - date; echo aviel Hello from the Kubernetes cluster
          restartPolicy: OnFailure
